version: 2.0
jobs:
  build-master-base:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # - run:
      #     name: Setup the repo (download openvino framework)
      #     command: make setup-repo
      - run:
          name: Fake docker cache
          command: docker pull $DOCKER_USER/sniper-master:base
      - run:
          name: Build our container & push it to docker
          command: |
            TAG=sniper-master:base
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/$TAG ./docker-master
            docker push $DOCKER_USER/$TAG
  build-master-demo:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # - run:
      #     name: Setup the repo (download openvino framework)
      #     command: make setup-repo
      - run:
          name: Fake docker cache
          command: docker pull $DOCKER_USER/sniper-master:demo
      - run:
          name: Build our container & push it to docker
          command: |
            TAG=sniper-master:demo
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/$TAG ./docker-master-demo
            docker push $DOCKER_USER/$TAG
  build-3000-base:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # - run:
      #     name: Setup the repo (download openvino framework)
      #     command: make setup-repo
      - run:
          name: Fake docker cache
          command: docker pull $DOCKER_USER/sniper-3000:base
      - run:
          name: Build our container & push it to docker
          command: |
            TAG=sniper-3000:base
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/$TAG ./docker-3000
            docker push $DOCKER_USER/$TAG
  build-3000-demo:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # - run:
      #     name: Setup the repo (download openvino framework)
      #     command: make setup-repo
      - run:
          name: Fake docker cache
          command: docker pull $DOCKER_USER/sniper-3000:demo
      - run:
          name: Build our container & push it to docker
          command: |
            TAG=sniper-3000:demo
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/$TAG ./docker-3000-demo
            docker push $DOCKER_USER/$TAG

workflows:
  version: 2
  build:
    jobs:
      # NOTE: Build only these images
      - build-master-demo
      - build-3000-demo
      # NOTE: Build everything sequentially
      # - build-master-base
      # - build-master-demo:
      #     requires:
      #       - build-master-base
      # - build-3000-base
      # - build-3000-demo:
          # requires:
          #   - build-3000-base
